// packages/post/src/root/Root.tsx
import React, {useCallback, useEffect, useState} from 'react';

import {PostPage} from 'pages';

export const Root = ({history}) => {
  const [historyContext, setHistoryContext] = useState<[]>([]);

  const goBack = useCallback(() => {
    if (history.length > 1) history.back();
    else history.push('/');
  }, [history]);

  useEffect(() => {
    const unsubscribe = history.subscribe(setHistoryContext);

    return () => {
      unsubscribe();
    };
  }, [history]);

  return (
    <>
      <span>{JSON.stringify(historyContext)}</span>
      <br />
      <button onClick={goBack}>go back</button>
      <PostPage />
    </>
  );
};

// packages/posts/src/root/Root.svelte
<script lang="ts">
  import {Posts} from "pages";
  import {onDestroy, onMount} from "svelte";

  export let theme;
  export let history;

  let historyContext = [];
  let unsubscribe;

  onMount(() => {
    unsubscribe = history.subscribe(context => historyContext = context)
  });

  onDestroy(() => {
    unsubscribe();
  })
</script>

{JSON.stringify(historyContext)}

<br/>

{JSON.stringify(theme)}

<br/>

{#if history.length > 1}
    <button on:click={() => history.back()}>go back</button>
{/if}

<Posts navigate={history.push}/>
